ln -s ~/.dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/.dotfiles/.config/nvim/ ~/.config/
ln -s ~/.dotfiles/.config/ranger ~/.config/
ln -s ~/.dotfiles/.config/i3 ~/.config/
ln -s ~/.dotfiles/.config/picom.conf ~/.config/picom.conf
ln -s ~/.dotfiles/.config/alacritty/ ~/.config/
ln -s ~/.dotfiles/.config/polybar/ ~/.config/
ln -s ~/.dotfiles/.config/rofi/ ~/.config/
ln -s ~/.dotfiles/.config/i3status ~/.config/
